#!/usr/bin/env ruby

require "bundler/setup"
require "name_sort"

sorter = NameSort::Sorter.new
{
  "|" => File.expand_path(File.join(File.dirname(__FILE__), "..", "data", "pipe.txt")),
  " " => File.expand_path(File.join(File.dirname(__FILE__), "..", "data", "space.txt")),
  "," => File.expand_path(File.join(File.dirname(__FILE__), "..", "data", "comma.txt"))
}.each_pair do |k,v|
  sorter.input(k,v)
end

puts "Output 1"
sorter.print_names("gender")
puts ""
puts "Output 2"
sorter.print_names("date_of_birth")
puts ""
puts "Output 3"
sorter.print_names("date_of_birth").reverse
puts ""
